application: p2d-css
version: 1
runtime: go
api_version: go1

default_expiration: "1s"

handlers:
#- url: /(.*\.(appcache|manifest))
#  mime_type: text/cache-manifest
#  static_files: html/\1
#  upload: html/(.*\.(appcache|manifest))
#  expiration: "0m"

#- url: /(.*\.atom)
#  mime_type: application/atom+xml
#  static_files: html/\1
#  upload: html/(.*\.atom)
#  expiration: "1h"

#- url: /(.*\.crx)
#  mime_type: application/x-chrome-extension
#  static_files: html/\1
#  upload: html/(.*\.crx)

- url: /(.*\.css)
  mime_type: text/css
  static_files: html/\1
  upload: html/(.*\.css)

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: html/\1
  upload: html/(.*\.eot)

#- url: /(.*\.htc)
#  mime_type: text/x-component
#  static_files: html/\1
#  upload: html/(.*\.htc)

- url: /(.*\.html)
  mime_type: text/html
  static_files: html/\1
  upload: html/(.*\.html)
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: html/\1
  upload: html/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: html/\1
  upload: html/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: html/\1
  upload: html/(.*\.json)
  expiration: "1h"

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: html/\1
  upload: html/(.*\.m4v)

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: html/\1
  upload: html/(.*\.mp4)

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: html/\1
  upload: html/(.*\.(ogg|oga))

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: html/\1
  upload: html/(.*\.ogv)

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: html/\1
  upload: html/(.*\.otf)

#- url: /(.*\.rss)
#  mime_type: application/rss+xml
#  static_files: html/\1
#  upload: html/(.*\.rss)
#  expiration: "1h"

#- url: /(.*\.safariextz)
#  mime_type: application/octet-stream
#  static_files: html/\1
#  upload: html/(.*\.safariextz)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: html/\1
  upload: html/(.*\.(svg|svgz))

#- url: /(.*\.swf)
#  mime_type: application/x-shockwave-flash
#  static_files: html/\1
#  upload: html/(.*\.swf)

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: html/\1
  upload: html/(.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: html/\1
  upload: html/(.*\.txt)

#- url: /(.*\.unity3d)
#  mime_type: application/vnd.unity
#  static_files: html/\1
#  upload: html/(.*\.unity3d)

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: html/\1
  upload: html/(.*\.webm)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: html/\1
  upload: html/(.*\.webp)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: html/\1
  upload: html/(.*\.woff)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: html/\1
  upload: html/(.*\.xml)
  expiration: "1h"

#- url: /(.*\.xpi)
#  mime_type: application/x-xpinstall
#  static_files: html/\1
#  upload: html/(.*\.xpi)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: html/\1
  upload: html/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: html/\1
  upload: html/(.*\.(mid|midi|mp3|wav))  

# windows files
#- url: /(.*\.(doc|exe|ppt|rtf|xls))
#  static_files: html/\1
#  upload: html/(.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: html/\1
  upload: html/(.*\.(bz2|gz|rar|tar|tgz|zip))

# index files
- url: /(.+)/
  static_files: html/\1/index.html
  upload: html/(.+)/index.html

# site root
- url: /
  static_files: html/index.html
  upload: html/index.html
  expiration: "15m"
